# Generated by Django 4.0.4 on 2022-05-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gradebook', '0002_alter_semester_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='Gradebook.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], default='S1', max_length=2),
        ),
    ]
