# Generated by Django 4.0.4 on 2022-05-29 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gradebook', '0004_lecturer_user_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gradebook.lecturer'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gradebook.course'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
